trigger:
- main

steps:
- script: npm install
  displayName: 'Installing dependencies'
#- script: ng build --configuration production --source-map=false --subresource-integrity --output-path=dist/full-stack
#  displayName: 'Building project'
- script: npm run dev
  displayName: 'Building project'
- powershell: |
    $version = (Get-Content .\version)
    echo "$version"
    echo "##vso[task.setvariable variable=version]$version"
  displayName: 'Read version'
- script: docker build -f ./docker/Dockerfile -t pfazekas1/$(projectName):$(version) -t pfazekas1/$(projectName):latest .
  displayName: 'Docker build'
- script: docker login -u$(dockerUser) -p$(dockerPass)
  displayName: 'Docker Hub login'
- script: |
    docker push pfazekas1/$(projectName):$(version)
    docker push pfazekas1/$(projectName):latest
  displayName: 'Docker push'
- powershell: |
    $file = "version"
    $fileVersion = (Get-Content $file | Select -First 1).Split(".")
    $fileVersion[2] = [int]$fileVersion[2] + 1
    $newVersion = $fileVersion -join "."
    $newVersion | Set-Content $file
    echo "$newVersion"
  displayName: 'Bump version'
- powershell: |
    git config --global user.name "$(gitUserName)"
    git config --global user.email "$(gitUserEmail)"
    git add version
    git commit -m "[Bump] version to: ${newVersion} [***NO_CI***]"
  displayName: 'Create and Git commit new version'
- powershell: |
    git remote set-url origin https://$(gitUserName):$(gitToken)@github.com/pfazekas1/FullStack.git
    git fetch origin master
    git push origin HEAD:master
  displayName: 'Git push'